name: E2E Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7.2-alpine  # Use stable Redis 7.2 version
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
          --health-start-period 30s

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.x

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Install redis-tools
      run: sudo apt-get update && sudo apt-get install -y redis-tools
    
    - name: Wait for Redis
      run: |
        echo "Waiting for Redis to be ready..."
        for i in {1..60}; do
          if redis-cli ping 2>/dev/null | grep -q PONG; then
            echo "Redis is ready!"
            redis-cli INFO server | grep redis_version || true
            break
          fi
          echo "Attempt $i/60: waiting for Redis..."
          sleep 2
        done
        
        # Final check
        if ! redis-cli ping 2>/dev/null | grep -q PONG; then
          echo "Redis failed to start properly"
          exit 1
        fi
    
    - name: Run E2E Tests
      run: go test -v -run TestEndToEndWithRealRedis
      env:
        REDIS_ADDR: localhost:6379

    - name: Run RDB Parsing Tests
      run: go test -v -run TestRDBParsingRobustness
      env:
        REDIS_ADDR: localhost:6379

    - name: Run Replication Benchmarks
      run: go test -v -bench BenchmarkReplicationThroughput -benchtime=3s
      env:
        REDIS_ADDR: localhost:6379

  e2e-with-auth:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.x

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Install redis-tools
      run: sudo apt-get update && sudo apt-get install -y redis-tools

    - name: Configure Redis with password
      run: |
        # Stop any existing Redis and start with auth using Docker
        docker stop redis-auth || true
        docker rm redis-auth || true
        docker run -d --name redis-auth -p 6379:6379 redis:7.2-alpine redis-server --requirepass testpassword123
        
        echo "Waiting for Redis with auth to be ready..."
        for i in {1..30}; do
          if redis-cli -a testpassword123 --no-auth-warning ping 2>/dev/null | grep -q PONG; then
            echo "Redis with auth is ready!"
            break
          fi
          echo "Attempt $i/30: waiting for Redis with auth..."
          sleep 2
        done
    
    - name: Wait for Redis with auth
      run: |
        # Final verification that Redis with auth is working
        if ! redis-cli -a testpassword123 --no-auth-warning ping 2>/dev/null | grep -q PONG; then
          echo "Redis with auth failed to start properly"
          docker logs redis-auth
          exit 1
        fi
        echo "Redis with auth verified!"
    
    - name: Run E2E Tests with Authentication
      run: go test -v -run TestEndToEndWithRealRedis
      env:
        REDIS_ADDR: localhost:6379
        REDIS_PASSWORD: testpassword123