name: Security Audit

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run security audit every Monday at 09:00 UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual triggering

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest
    name: Vulnerability Scanning
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.5'
        
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          
    - name: Download dependencies
      run: go mod download
      
    - name: Verify dependencies
      run: go mod verify
      
    - name: Install govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@latest
      
    - name: Run govulncheck
      run: govulncheck ./...
      continue-on-error: false
      
    - name: Install staticcheck for static analysis
      run: go install honnef.co/go/tools/cmd/staticcheck@latest
      
    - name: Run staticcheck security analysis
      run: staticcheck ./...
      continue-on-error: true
        
  dependency-scan:
    runs-on: ubuntu-latest
    name: Dependency Security Check
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.5'
        
    - name: Audit Go modules
      run: |
        echo "Checking for Go module security issues..."
        go mod tidy
        go mod verify
        
        # Check for any retracted modules
        go list -retracted -f '{{.Path}}: {{.Retracted}}' all || true
        
  code-quality-scan:
    runs-on: ubuntu-latest
    name: Code Quality & Security
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.5'
        
    - name: Run go vet
      run: go vet ./...
      
    - name: Check for hardcoded secrets
      run: |
        echo "Checking for potential hardcoded secrets..."
        # Use the enhanced security audit script
        chmod +x scripts/security-audit.sh
        # Run just the secret detection part by running full audit and checking exit code
        ./scripts/security-audit.sh
        
    - name: Check for debug/logging issues
      run: |
        echo "Checking for potential information disclosure in logs..."
        # Use refined patterns that exclude legitimate logger code
        if grep -r "fmt\.Print" --include="*.go" . | grep -v "_test.go" | grep -v "//" | grep -v "examples/"; then
          echo "⚠️  Found fmt.Print statements that could leak information"
          exit 1
        fi
        
        if grep -r "log\.Print" --include="*.go" . | grep -v "_test.go" | grep -v "//" | grep -v "examples/" | grep -v "interfaces.go"; then
          echo "⚠️  Found log.Print statements that could leak information"
          exit 1
        fi
        
        echo "✅ No obvious logging issues found"
        
    - name: Check for unsafe operations
      run: |
        echo "Checking for unsafe operations..."
        # Check for unsafe operations but allow those marked as safe
        UNSAFE_FOUND=false
        if grep -r "unsafe\." --include="*.go" . | grep -v "_test.go"; then
          # Check if any unsafe operations are not marked as safe
          while IFS= read -r line; do
            if [ -n "$line" ]; then
              FILE=$(echo "$line" | cut -d: -f1)
              LINENUM=$(echo "$line" | cut -d: -f2)
              # Check for safe comment in the 3 lines before
              if ! sed -n "$((LINENUM-3)),$((LINENUM-1))p" "$FILE" 2>/dev/null | grep -q "// safe:"; then
                echo "⚠️  Found unsafe operation: $line"
                UNSAFE_FOUND=true
              fi
            fi
          done < <(grep -r -n "unsafe\." --include="*.go" . | grep -v "_test.go" | grep -v "// safe:")
          
          if [ "$UNSAFE_FOUND" = true ]; then
            echo "⚠️  Found unsafe operations - review carefully"
          else
            echo "✅ All unsafe operations are properly marked as safe"
          fi
        else
          echo "✅ No unsafe operations found"
        fi
        
        if grep -r "os\.Setenv" --include="*.go" . | grep -v "_test.go"; then
          echo "⚠️  Found os.Setenv calls - review for security implications"
        else
          echo "✅ No environment manipulation found"
        fi

  build-and-test:
    runs-on: ubuntu-latest
    name: Security-focused Build & Test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.5'
        
    - name: Build with security flags
      run: |
        echo "Building with security-focused compiler flags..."
        go build -buildmode=pie -ldflags="-s -w" ./...
        
    - name: Run tests with race detection
      run: go test -race -coverprofile=coverage.out ./...
      
    - name: Run fuzzing tests (if available)
      run: |
        # Look for fuzz tests and run them briefly
        if find . -name "*_test.go" -exec grep -l "func Fuzz" {} \; | head -1; then
          echo "Running fuzz tests..."
          go test -fuzz=. -fuzztime=30s ./... || echo "Fuzz tests completed"
        else
          echo "No fuzz tests found"
        fi